---
- name: create directories
  become: yes
  become_user: root
  with_items:
    - { d: '{{couchdb_dir}}/var/run', m: '0700' }
  file: >-
    path={{item.d}}
    state=directory
    owner={{couchdb_user}}
    group={{couchdb_group}}
    mode={{item.m}}

- name: install init.d service
  become: yes
  become_user: root
  register: couchdb_service_modified
  with_items:
    - etc/init.d/couchdb2
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0755

- name: Update rc.d
  shell: update-rc.d couchdb2 defaults

- name: Start CouchDB service
  service: name=couchdb2 state=started
